# Generated by Django 3.2.6 on 2021-08-05 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerId', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=100)),
                ('CustomerAcronym', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('InvoiceId', models.AutoField(primary_key=True, serialize=False)),
                ('InvoiceNumber', models.CharField(max_length=30)),
                ('InvoiceURL', models.URLField()),
                ('InvoiceAmount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('InvoiceCustomer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='InvoicingWeb.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('PartnerId', models.AutoField(primary_key=True, serialize=False)),
                ('PartnerName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerInvoice',
            fields=[
                ('InvoiceId', models.AutoField(primary_key=True, serialize=False)),
                ('InvoiceNumber', models.CharField(max_length=30)),
                ('InvoiceURL', models.URLField()),
                ('InvoiceAmount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('CustomerInvoice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='InvoicingWeb.customerinvoice')),
                ('InvoicePartner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='InvoicingWeb.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ProjectId', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=200)),
                ('ProjectCustomer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='InvoicingWeb.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('ResourceId', models.AutoField(primary_key=True, serialize=False)),
                ('ResourceName', models.CharField(max_length=100)),
                ('ResourceEmail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectResource',
            fields=[
                ('ProjectResourceId', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectResourceRateToCustomer', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ProjectResourceTransferRate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ProjectResourceProject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='InvoicingWeb.project')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerInvoiceLineItem',
            fields=[
                ('PILineItemId', models.AutoField(primary_key=True, serialize=False)),
                ('PILineItemAmount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('PILineItemHours', models.DecimalField(decimal_places=2, max_digits=12)),
                ('PILineItemComments', models.CharField(max_length=127)),
                ('PILineItemInvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvoicingWeb.partnerinvoice')),
                ('PILineItemResource', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='InvoicingWeb.resource')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInvoiceLineItem',
            fields=[
                ('CInvoiceLineItemId', models.AutoField(primary_key=True, serialize=False)),
                ('CInvoiceLineItemAmount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('CInvoiceLineItemHours', models.DecimalField(decimal_places=2, max_digits=12)),
                ('CInvoiceLineItemComments', models.CharField(max_length=127)),
                ('CInvoiceLineItemInvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvoicingWeb.customerinvoice')),
                ('CInvoiceLineItemResource', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='InvoicingWeb.resource')),
            ],
        ),
    ]
