# Generated by Django 3.2.6 on 2021-08-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoicingWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoice',
            name='InvoicePaid',
            field=models.BooleanField(default=False),
        ),
    ]
