# Generated by Django 3.2.6 on 2021-08-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoicingWeb', '0002_customerinvoice_invoicepaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remittance',
            fields=[
                ('RemittanceId', models.AutoField(primary_key=True, serialize=False)),
                ('RemittanceDate', models.DateField(null=True)),
                ('RemittanceConfirmationCode', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='InvoiceFromDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='InvoiceIssueDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='InvoiceToDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='partnerinvoice',
            name='InvoiceFromDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='partnerinvoice',
            name='InvoiceIssueDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='partnerinvoice',
            name='InvoiceToDate',
            field=models.DateField(null=True),
        ),
    ]
