# Generated by Django 3.2.6 on 2021-09-13 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvoicingWeb', '0003_auto_20210812_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinvoice',
            name='InvoicePaid',
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='InvoicePaidDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='partnerinvoice',
            name='CoveredByRemittance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='InvoicingWeb.remittance'),
        ),
        migrations.AddField(
            model_name='remittance',
            name='RemittanceAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
