# Generated by Django 3.2.6 on 2021-09-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoicingWeb', '0004_auto_20210913_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinvoice',
            name='InvoiceAmount',
        ),
        migrations.RemoveField(
            model_name='partnerinvoice',
            name='InvoiceAmount',
        ),
        migrations.AlterField(
            model_name='customerinvoicelineitem',
            name='CInvoiceLineItemComments',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
