# Generated by Django 3.2.6 on 2021-09-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoicingWeb', '0005_auto_20210913_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvoicelineitem',
            name='CInvoiceLineItemComments',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='partnerinvoicelineitem',
            name='PILineItemComments',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
