# Generated by Django 3.2.6 on 2021-09-29 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvoicingWeb', '0006_auto_20210913_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerinvoice',
            name='CoveredByRemittance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='InvoicingWeb.remittance'),
        ),
    ]
