# Generated by Django 3.2.6 on 2021-11-04 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvoicingWeb', '0008_rename_cinvoicelineiteminvoice_customerinvoicelineitem_customerinvoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerinvoicelineitem',
            old_name='PILineItemInvoice',
            new_name='PartnerInvoice',
        ),
    ]
