# Generated by Django 3.2.6 on 2021-11-04 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvoicingWeb', '0009_rename_pilineiteminvoice_partnerinvoicelineitem_partnerinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerinvoice',
            name='CustomerInvoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='InvoicingWeb.customerinvoice'),
        ),
    ]
