# Generated by Django 3.2.6 on 2021-11-11 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvoicingWeb', '0012_auto_20211111_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinvoicelineitem',
            old_name='CInvoiceLineItemComments',
            new_name='Comments',
        ),
        migrations.RenameField(
            model_name='customerinvoicelineitem',
            old_name='CInvoiceLineItemAmount',
            new_name='TotalAmount',
        ),
        migrations.RenameField(
            model_name='customerinvoicelineitem',
            old_name='CInvoiceLineItemHours',
            new_name='TotalHours',
        ),
        migrations.RemoveField(
            model_name='customerinvoicelineitem',
            name='CInvoiceLineItemResource',
        ),
    ]
