# Generated by Django 3.2.6 on 2021-11-11 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvoicingWeb', '0013_auto_20211111_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoicelineitem',
            name='Resource',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='InvoicingWeb.resource'),
        ),
    ]
