# Generated by Django 3.2.6 on 2021-11-11 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvoicingWeb', '0015_alter_customerinvoicelineitem_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinvoicelineitem',
            name='Resource',
        ),
    ]
