# Generated by Django 3.2.6 on 2021-11-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoicingWeb', '0017_customerinvoicelineitem_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoicelineitem',
            name='Rate',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
