# Generated by Django 3.2.6 on 2021-11-12 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvoicingWeb', '0018_customerinvoicelineitem_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerinvoicelineitem',
            old_name='PILineItemComments',
            new_name='Comments',
        ),
        migrations.RenameField(
            model_name='partnerinvoicelineitem',
            old_name='PILineItemResource',
            new_name='Resource',
        ),
        migrations.RenameField(
            model_name='partnerinvoicelineitem',
            old_name='PILineItemAmount',
            new_name='TotalAmount',
        ),
        migrations.RenameField(
            model_name='partnerinvoicelineitem',
            old_name='PILineItemHours',
            new_name='TotalHours',
        ),
    ]
