# Generated by Django 3.2.6 on 2021-11-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoicingWeb', '0019_auto_20211111_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerinvoicelineitem',
            name='Rate',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
