# Generated by Django 3.2.6 on 2021-12-09 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvoicingWeb', '0022_auto_20211111_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceRate',
            fields=[
                ('ProjectResourceId', models.AutoField(primary_key=True, serialize=False)),
                ('RateToCustomer', models.DecimalField(decimal_places=2, max_digits=12)),
                ('TransferRate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('FromDate', models.DateField(null=True)),
                ('ToDate', models.DateField(null=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='InvoicingWeb.customer')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='InvoicingWeb.project')),
                ('Resource', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='InvoicingWeb.resource')),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectResource',
        ),
    ]
