# Generated by Django 3.2.6 on 2022-01-12 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvoicingWeb', '0028_auto_20220105_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerinvoicelineitem',
            name='Rate',
        ),
        migrations.RemoveField(
            model_name='partnerinvoicelineitem',
            name='Rate_currency',
        ),
    ]
