# Generated by Django 3.2.6 on 2022-01-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoicingWeb', '0029_auto_20220111_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerinvoicelineitem',
            old_name='TotalHours',
            new_name='HoursAsPrinted',
        ),
        migrations.RemoveField(
            model_name='partnerinvoicelineitem',
            name='TotalAmount',
        ),
        migrations.RemoveField(
            model_name='partnerinvoicelineitem',
            name='TotalAmount_currency',
        ),
        migrations.AddField(
            model_name='partnerinvoicelineitem',
            name='RateAsPrinted',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
            preserve_default=False,
        ),
    ]
