# Generated by Django 3.2.6 on 2022-01-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoicingWeb', '0031_auto_20220112_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerinvoicelineitem',
            name='Rate_currency',
        ),
        migrations.RemoveField(
            model_name='partnerinvoicelineitem',
            name='TotalAmount_currency',
        ),
        migrations.AlterField(
            model_name='partnerinvoicelineitem',
            name='Rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partnerinvoicelineitem',
            name='TotalAmount',
            field=models.DecimalField(decimal_places=2, default=9, max_digits=14),
            preserve_default=False,
        ),
    ]
